To generate the random values for the matrix 


In [1]:
import numpy as np 


In [2]:
x=[[1,0,1,0],[1,0,1,1],[0,1,0,1]]

In [3]:
x=np.array(x)

In [4]:
print(x)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]


In [5]:
wh=np.random.rand(4,3)

In [6]:
print(wh)

[[0.23766254 0.8780987  0.32631984]
 [0.7529796  0.32338666 0.17733758]
 [0.66168082 0.74376316 0.04542648]
 [0.53296524 0.81355506 0.54935033]]


In [7]:
bh=np.random.rand(1,3)

In [8]:
print(bh)

[[0.11961813 0.56674109 0.82963095]]


In [10]:
hidden_layer_input=(np.dot(x,wh))+bh

In [11]:
print(hidden_layer_input)

[[1.01896149 2.18860295 1.20137727]
 [1.55192673 3.00215801 1.7507276 ]
 [1.40556297 1.70368281 1.55631886]]


In [12]:
def sigmoid (hidden_layer_input): return 1/(1 + np.exp(-hidden_layer_input))  

In [13]:
hiddenlayer_activations=sigmoid(hidden_layer_input)

In [14]:
print(hiddenlayer_activations)

[[0.73477026 0.89922137 0.7687697 ]
 [0.82519184 0.95267152 0.85204455]
 [0.80306516 0.84601512 0.8258245 ]]


In [15]:
wout=np.random.rand(3,1)

In [16]:
print(wout)

[[0.99188552]
 [0.52117685]
 [0.85179651]]


In [17]:
bout=np.random.rand(1,1)

In [18]:
print(bout)

[[0.6605259]]


output_layer_input = matrix_dot_product (hiddenlayer_activations * wout ) + bout output = sigmoid(output_layer_input)

In [19]:
output_layer=np.dot(hiddenlayer_activations,wout)+bout

In [20]:
output_layer_input=sigmoid(output_layer)

In [21]:
print(output_layer_input)

[[0.92503586]
 [0.93710335]
 [0.93095372]]


In [30]:
y=[[1],[1],[0]]

In [31]:
y=np.array(y)

In [32]:
E=y-output_layer_input

In [33]:
print(E)

[[ 0.07496414]
 [ 0.06289665]
 [-0.93095372]]


In [34]:
def sigmoid_(x): return x * (1 - x)             # derivative of sigmoid


In [39]:
slope_output_layer=sigmoid_(E)

In [40]:
print(slope_output_layer)

[[ 0.06934452]
 [ 0.05894066]
 [-1.79762854]]


In [41]:
slope_hidden_layer=sigmoid_(hiddenlayer_activations)

In [42]:
print(slope_hidden_layer)

[[0.19488292 0.09062229 0.17776285]
 [0.14425027 0.04508849 0.12606464]
 [0.15815151 0.13027354 0.1438384 ]]


In [45]:
d_output = E * slope_output_layer*0.1

In [46]:
print(d_output)

[[0.00051984]
 [0.00037072]
 [0.1673509 ]]


In [50]:
Error_at_hidden_layer=np.dot(d_output,np.transpose(wout))

In [51]:
print(Error_at_hidden_layer)

[[0.00051562 0.00027093 0.00044279]
 [0.00036771 0.00019321 0.00031578]
 [0.16599293 0.08721941 0.14254891]]


In [54]:
d_hiddenlayer= np.dot(Error_at_hidden_layer ,slope_hidden_layer)
print(d_hiddenlayer)


[[2.09594640e-04 1.16626373e-04 1.89502516e-04]
 [1.49471013e-04 8.31713167e-05 1.35142450e-04]
 [6.74749366e-02 3.75456030e-02 6.10066664e-02]]


wout = wout + matrix_dot_product (hiddenlayer_activations.Transpose, d_output) * learning_rate
wh = wh+ matrix_dot_product (X.Transpose,d_hiddenlayer) * learning_rate

In [55]:
wout_updated=wout + np.dot(np.transpose(hiddenlayer_activations), d_output) * 0.1
print(wout_updated)

[[1.00539368]
 [0.53541705]
 [0.86568831]]


In [56]:
wh_updated=wh+np.dot(np.transpose(x),d_hiddenlayer)*0.1
print(wh_updated)

[[0.23767789 0.87810202 0.32633169]
 [0.75560481 0.3245229  0.17938798]
 [0.66169617 0.74376649 0.04543833]
 [0.53559574 0.81469217 0.55140471]]


bh = bh + sum(d_hiddenlayer, axis=0) * learning_rate
bout = bout + sum(d_output, axis=0)*learning_rate

In [59]:
bh_updated= bh + (d_hiddenlayer) * 0.1
print(bh_updated)

[[0.11962818 0.56674355 0.82963882]
 [0.11962344 0.56674196 0.82963493]
 [0.12224334 0.56787733 0.83168135]]


In [60]:
bout_updated = bout + (d_output)*0.1
print(bout_updated)

[[0.66057788]
 [0.66056297]
 [0.67726099]]
